sudo: required

services:
  - docker

script:
  - |
    set -e
    for path in `find . -name Dockerfile`; do
        echo $path
        docker run --rm -i pdericson/hadolint < $path
    done
  - |
    docker run --rm -v "$PWD":/mnt python:3-alpine sh -c 'pip install flake8 && flake8 --ignore=E501 /mnt'
